version: 2

builds:
  - binary: sport
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=mod

# Include additional files (Node.js scripts) in the release artifacts
extra_files:
  - cmd/fotball.js
  - cmd/hoydepunkter.js
  - cmd/vintersport.js

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: sport
    homepage: "https://github.com/hbleie/sportskalender-in-terminal"
    repository:
      owner: hbleie
      name: homebrew-hbleie

checksum:
  name_template: 'checksums.txt'
