version: 2

builds:
  - binary: sportskalender-in-terminal
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=mod

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: sportskalender-in-terminal
    homepage: "https://github.com/hbleie/sportskalender-in-terminal"
    repository:
      owner: hbleie
      name: homebrew-hbleie

checksum:
  name_template: 'checksums.txt'
