name: Create Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Ensure the script has the correct permissions (make it executable)
      - name: Set executable permissions on the zsh script
        run: chmod +x sportskalender-in-terminal.plugin.zsh

      # Step 3: Create a tarball of the CLI tool
      - name: Create a tarball
        run: |
          mkdir -p dist
          tar -czvf dist/sportskalender-in-terminal-${{ github.event.release.tag_name }}.tar.gz sportskalender-in-terminal.plugin.zsh

      # Step 4: Upload the tarball as a release asset
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/sportskalender-in-terminal-${{ github.event.release.tag_name }}.tar.gz
          asset_name: sportskalender-in-terminal-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip
